sudo: false
language: node_js
node_js:
  - 'stable'
  - '0.12'
  - '0.10'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libstdc++-4.8-dev
before_install:
  - export CXX="g++-4.8" CC="gcc-4.8"
